name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:   # 👈 adds the button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: configure
        run: ./configure

      - name: Compile
        run: make

      - name: Run check
        run: make check

      - name: Run distcheck
        run: make distcheck
